gitki:
    git:
        repository: "/tmp/gitki_test_repository/"
spring:
  datasource:
    url: "jdbc:hsqldb:mem:test"
wicket:
  core:
    settings:
      general:
        configuration-type: development