gitki:
    repository: "${user.home}/gitki/default/repository/"
    viewMappings:
        txt: "net.dontdrinkandroot.gitki.wicket.page.file.view.TextViewPage"
        csv: "net.dontdrinkandroot.gitki.wicket.page.file.view.TextViewPage"
        xml: "net.dontdrinkandroot.gitki.wicket.page.file.view.TextViewPage"
        java: "net.dontdrinkandroot.gitki.wicket.page.file.view.TextViewPage"
        yml: "net.dontdrinkandroot.gitki.wicket.page.file.view.TextViewPage"
        properties: "net.dontdrinkandroot.gitki.wicket.page.file.view.TextViewPage"
        md: "net.dontdrinkandroot.gitki.wicket.page.file.view.MarkdownViewPage"
        jpg: "net.dontdrinkandroot.gitki.wicket.page.file.view.ImageViewPage"
        jpeg: "net.dontdrinkandroot.gitki.wicket.page.file.view.ImageViewPage"
        png: "net.dontdrinkandroot.gitki.wicket.page.file.view.ImageViewPage"
        gif: "net.dontdrinkandroot.gitki.wicket.page.file.view.ImageViewPage"
    editMappings:
        txt: "net.dontdrinkandroot.gitki.wicket.page.file.edit.TextEditPage"
        csv: "net.dontdrinkandroot.gitki.wicket.page.file.edit.TextEditPage"
        xml: "net.dontdrinkandroot.gitki.wicket.page.file.edit.TextEditPage"
        properties: "net.dontdrinkandroot.gitki.wicket.page.file.edit.TextEditPage"
        md: "net.dontdrinkandroot.gitki.wicket.page.file.edit.MarkdownEditPage"
    indexFileMappings:
       "md": "net.dontdrinkandroot.gitki.wicket.component.bspanel.index.MarkdownIndexFilePanel"
       "txt": "net.dontdrinkandroot.gitki.wicket.component.bspanel.index.TextIndexFilePanel"
    indexFiles:
        - "README.md"
        - "readme.md"
        - "INDEX.md"
        - "index.md"
        - "README.txt"
        - "readme.txt"
        - "INDEX.txt"
        - "index.txt"
#management:
#  context-path: "/manage"
wicket:
  core:
    settings:
      general:
        configuration-type: deployment
      markup:
        strip-wicket-tags: true
  web:
    servlet:
      dispatcher-types:
        - request
        - error
        - async
spring:
  datasource:
    username: sa
    password:
    url: "jdbc:hsqldb:file:${user.home}/gitki/default/database/gitki"
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    whitelabel:
      enabled: false